- id: pyrefly-typecheck-system
  name: pyrefly-typecheck-system
  description: "Run `pyrefly check` using the system-installed `pyrefly`."
  entry: pyrefly check
  language: system
  types_or: [python, pyi]
  pass_filenames: false
  require_serial: true
  stages: [pre-commit, pre-merge-commit, pre-push, manual]

- id: pyrefly-typecheck-specific-version
  name: pyrefly-typecheck-specific-version
  description: "Run `pyrefly check` with user-specified version via additional_dependencies."
  entry: pyrefly check
  language: python
  types_or: [python, pyi]
  pass_filenames: false
  require_serial: true
  stages: [pre-commit, pre-merge-commit, pre-push, manual]
